In [1]:
import numpy as np
import numpy.typing as npt
from scipy.spatial.transform import Rotation as R
from scipy.spatial.transform import Slerp

import util

# Rotvec and quaternion

In [22]:
def convert_quat_xyzw_to_wxyz(q: np.ndarray) -> np.ndarray:
    """
    Converts a quaternion from [x, y, z, w] format to [w, x, y, z] format.
    """
    q = np.asarray(q, dtype=np.float64)
    return np.array([q[3], q[0], q[1], q[2]], dtype=np.float64)

def axis_angle_quat(axis: np.ndarray, angle_rad: float):
    """
    Converts axis angle to quaternion in [w, x, y, z] format.
    
    Usage example:
    ```
    axis = [1, 0.2, 0.1,]
    angle = np.deg2rad(90)
    custom_quat = axis_angle_quat(axis, angle)
    
    normalized_axis = np.array(axis) / np.linalg.norm(axis)
    rot_vector = normalized_axis * angle
    scipy_quat = R.from_rotvec(rot_vector).as_quat() # [x, y, z, w]
    
    custom_reordered = np.append(custom_quat[1:], custom_quat[0])
    assert np.allclose(custom_reordered, scipy_quat)
    ```
    """
    assert len(axis) == 3, "Axis must be a 3D vector"
    
    axis = np.asarray(axis, dtype=np.float64)
    norm = np.linalg.norm(axis)

    # Handle zero rotation / uninitialized vectors safely
    if np.isclose(norm, 0.0):
        w, xyz = 1.0, np.zeros(3, dtype=np.float64)
        return np.array([w, *xyz], dtype=np.float64)

    axis = axis / norm
    half = angle_rad / 2.0
    
    w = np.cos(half)
    xyz = np.sin(half) * axis
    return np.array([w, *xyz], dtype=np.float64)

In [ ]:
def quat_mul(q1: np.ndarray, q2: np.ndarray) -> np.ndarray:
    """
    quat_mul with mujoco
    
    Example usage:
    ```python
    q1_xyzw = np.array([1, 0.2, 0.1, np.deg2rad(90)], dtype=np.float64)
    q2_xyzw = np.array([0.5, 0.1, 1, np.deg2rad(45)], dtype=np.float64)

    rot1 = R.from_quat(q1_xyzw)
    rot2 = R.from_quat(q2_xyzw)

    combined_rot = rot1 * rot2
    combined_rot_quat_xyzw = combined_rot.as_quat()

    q1_mj = convert_quat_xyzw_to_wxyz(q1_xyzw)
    q2_mj = convert_quat_xyzw_to_wxyz(q2_xyzw)

    q1_mj /= np.linalg.norm(q1_mj)
    q2_mj /= np.linalg.norm(q2_mj)

    mj_quat = quat_mul(q1_mj, q2_mj)
    scipy_quat_wxyz = convert_quat_xyzw_to_wxyz(combined_rot_quat_xyzw)

    print("SciPy quaternion:", scipy_quat_wxyz)
    print("MuJoCo quaternion:", mj_quat)
    
    assert np.allclose(scipy_quat_wxyz, mj_quat) or np.allclose(scipy_quat_wxyz, -mj_quat)
    ```
    """
    import mujoco

    result = np.zeros(4, dtype=np.float64)
    mujoco.mju_mulQuat(result, q1, q2)
    return result

SciPy quaternion: [ 0.23885303  0.68530415 -0.24747002  0.64192371]
MuJoCo quaternion: [ 0.23885303  0.68530415 -0.24747002  0.64192371]


In [ ]:
quat_mul([0, 1, 0, 1], [0, 0, 1, 1])

# Rotations (Euler and Rotatation vectors)

In [9]:
# from euler, extrinsic rotation
## single axis
R.from_euler(seq='x', angles=90, degrees=True).as_matrix()   
R.from_euler('x', [90], degrees=True).as_matrix()  
R.from_euler('x', [90, 45, 30], degrees=True).as_matrix() 

## multi axis
R.from_euler('xyz', [90, 45, 30], degrees=True).as_matrix()
R.from_euler('xyz', [[90, 45, 30]], degrees=True).as_matrix()
R.from_euler('xyz', [[90, 45, 30], [35, 45, 90]], degrees=True).as_matrix()

array([[[ 6.12372436e-01,  6.12372436e-01,  5.00000000e-01],
        [ 3.53553391e-01,  3.53553391e-01, -8.66025404e-01],
        [-7.07106781e-01,  7.07106781e-01,  5.55111512e-17]],

       [[ 1.66533454e-16, -8.19152044e-01,  5.73576436e-01],
        [ 7.07106781e-01,  4.05579788e-01,  5.79227965e-01],
        [-7.07106781e-01,  4.05579788e-01,  5.79227965e-01]]])

Assuming universal robot joints are in Base: 0, -91.66, -68.04, -110.30, 90, Wrist 3: 0 </br>
we can use `var:=get_actual_tcp_pose()`  to get the actual pose of tcp wrt to base </br>
we'll get p[0.47987, -0.1333, 0.6238, 2.22144, -2.22144, -0] </br>

<p align="center">
  <img src=".\imgs\2024-12-21 204339.png" alt="" width="400" style="max-width:100%;">
</p>

code:
```python
x = R.from_rotvec([2.22144, -2.22144, 0]).as_matrix()
util.print_array(x, True, 3)  

"""
[[ 0. -1. -0.]
 [-1.  0. -0.]
 [ 0.  0. -1.]]

1st col: indicates x axis of tcp is in -1 dir of y axis of base
2nd col: indicates y axis of tcp is in -1 dir of x axis of base
3rd col: z axis of tcp is in -1 dir of z axis of base
"""

```
In the following, we can see RPY is [180.  -0. -90.]. The code below confirms that we need to use `"xyz"` seq in `as_euler`
<p align="center">
  <img src=".\imgs\2024-12-21 205258.png" alt="" width="400" style="max-width:100%;">
</p>

code:
```python
x = R.from_rotvec([2.22144, -2.22144, 0]).as_euler("xyz", degrees=True)
util.print_array(x, True, 3) # [180.  -0. -90.]
```


In [10]:
x = R.from_rotvec([2.22144, -2.22144, 0]).as_euler("xyz", degrees=True)
util.print_array(x, True, 3)  

[180.  -0. -90.]


# Universal robot 

## Calculating pose transformation with python vs using PolyScope 
- refer to Obsidian Notes for full setup of Polyscope. The code below will still work

In [11]:
"""
According to Copilot, we can also use cv2.Rodrigues

def pose_to_homogeneous(pose):
    x, y, z, rx, ry, rz = pose
    R, _ = cv2.Rodrigues(np.array([rx, ry, rz]))
    T = np.eye(4)
    T[:3, :3] = R
    T[:3, 3] = [x, y, z]
    return T

def homogeneous_to_pose(T):
    R = T[:3, :3]
    t = T[:3, 3]
    rx, ry, rz = cv2.Rodrigues(R)[0].flatten()
    return [t[0], t[1], t[2], rx, ry, rz]
"""

def pose_to_TMatrix(pose: list[float]|npt.ArrayLike):
    x, y, z, rx, ry, rz = pose
    rot = R.from_rotvec([rx, ry, rz])
    m = np.eye(4)
    m[:3, :3] = rot.as_matrix()
    m[:3, 3] = [x, y, z]
    return m

def TMatrix_to_pose(m: npt.NDArray):
    rot = R.from_matrix(m[:3, :3])
    t = m[:3, 3]
    rx, ry, rz = rot.as_rotvec()
    return [t[0], t[1], t[2], rx, ry, rz]

def inverse_TMatrix(T):
    R = T[:3, :3]
    t = T[:3, 3]
    R_inv = R.T
    t_inv = -np.dot(R_inv, t)
    T_inv = np.eye(4)
    T_inv[:3, :3] = R_inv
    T_inv[:3, 3] = t_inv
    return T_inv

# starting tcp pose relative to base frame (movej, variable position)
pose_A = [0.03979, -0.44943, 0.48438, -0.00122, 3.14159, 0]

# delta pose relative to A
delta_ab = [0.18375, 0.01395, 0.23235, 0, 0, 0]
delta_ac = [0, 0, 0.35, 0,0,0]

"""
Typically, without knowing the transofrmation matrix from B to C, 
all we can do is:

movej(pose_A)
movel(pose_B)
movej(pose_A)
movel(pose_C)

To move directly from B to C (there by skipping the 2nd movej(A)), we need
to perform the following calculation:

T_{AC} = T_{AB}\;T_{BC} \\
T^{-1}_{AB}\;T_{AC} = T_{BC}

Steps:
1. Convert the pose to a homogeneous transformation matrix.
2. Calculate the inverse of T_{AB}.
3. Multiply the inverse of T_{AB} with T_{AC}.
4. For use with cobot on PolyScope, convert the resulting matrix back to a pose.
5. Use moveL with this pose.
"""

t_AB = pose_to_TMatrix(delta_ab)
t_AC = pose_to_TMatrix(delta_ac)
t_ab_inv = inverse_TMatrix(t_AB) # pose_inv(t_AB) in Polyscope
t_bc = t_ab_inv @ t_AC # pose_trans(t_ab_inv, t_AC) in Polyscope

delta_bc = TMatrix_to_pose(t_bc)
print("delta_bc")
util.print_array(np.array(delta_bc), True, precision=7)
# [-0.18375 -0.01395  0.11765  0.       0.       0.     ]

delta_bc
[-0.18375 -0.01395  0.11765  0.       0.       0.     ]


## Slerp

In [2]:
def test_slerp():
    # Two rotations
    r0 = R.from_euler('z', 0, degrees=True)
    r1 = R.from_euler('z', 90, degrees=True)

    # Stack them
    rots = R.concatenate([r0, r1])

    times = [0, 1]
    slerp = Slerp(times, rots)

    interp_times = np.linspace(0, 1, 5)
    interp_rots = slerp(interp_times)

    print(f"{interp_times = }")
    print(f"{slerp([interp_times[-1]]).as_euler('zxy', degrees=True) =}")
    print(f"{r0 =}")
    print(interp_rots.as_euler('zxy', degrees=True))

test_slerp()

def test_slerp1():
    times = [0, 1, 2]

    # create 3 rotations: 0, 90, and 180 degrees about z-axis
    rots = R.from_euler('z', [0, 90, 180], degrees=True)

    slerp = Slerp(times, rots)

    interp_times = np.linspace(0, 2, 9)
    interp_rots = slerp(interp_times)

    print(f"{interp_times = }")
    print(f"{rots = }")
    print(interp_rots.as_euler('zxy', degrees=True))
    
test_slerp1()


interp_times = array([0.  , 0.25, 0.5 , 0.75, 1.  ])
slerp([interp_times[-1]]).as_euler('zxy', degrees=True) =array([[90.,  0.,  0.]])
r0 =<scipy.spatial.transform._rotation.Rotation object at 0x0000019671A8FA50>
[[ 0.   0.   0. ]
 [22.5  0.   0. ]
 [45.   0.   0. ]
 [67.5  0.   0. ]
 [90.   0.   0. ]]
interp_times = array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])
rots = <scipy.spatial.transform._rotation.Rotation object at 0x0000019671A8FD20>
[[  0.    0.    0. ]
 [ 22.5   0.    0. ]
 [ 45.    0.    0. ]
 [ 67.5   0.    0. ]
 [ 90.    0.    0. ]
 [112.5   0.    0. ]
 [135.    0.    0. ]
 [157.5   0.    0. ]
 [180.    0.    0. ]]
